language: php

matrix:
  include:
    - php: 7.2
      env: LARAVEL='7.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.2
      env: LARAVEL='7.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-stable'
    - php: 7.3
      env: LARAVEL='7.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3
      env: LARAVEL='7.*' TESTBENCH='4.*' COMPOSER_FLAGS='--prefer-stable'
  fast_finish: true

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini || true

before_install:
  - sudo apt-get update
  - travis_retry composer self-update
  - travis_retry composer require "laravel/framework:${LARAVEL}" "orchestra/testbench:${TESTBENCH}" --no-interaction --no-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction --no-suggest

script:
  - vendor/bin/phpunit

branches:
  only:
    - develop
