sudo: required

language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - yes
  - travis_retry composer update --prefer-source $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit

branches:
  only:
    - develop
